import os
from sqlalchemy import create_engine, Column, Integer, String, Float, JSON, ForeignKey, DateTime
from sqlalchemy.orm import declarative_base, sessionmaker
from sqlalchemy.sql import func

# Database connection string (defaulting to the docker container settings)
DB_URL = os.getenv("DATABASE_URL", "postgresql://admin:adminpassword@localhost:5432/credit_risk_db")

engine = create_engine(DB_URL)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()

class Applicant(Base):
    __tablename__ = "applicants"
    
    id = Column(Integer, primary_key=True, index=True)
    customer_id = Column(String, unique=True, index=True)
    annual_income = Column(Float)
    outstanding_debt = Column(Float)
    credit_score = Column(String)
    employment_type = Column(String)
    # Storing the raw JSON for the rest of the unstructured inputs
    raw_data = Column(JSON)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

class RiskAssessment(Base):
    __tablename__ = "risk_assessments"
    
    id = Column(Integer, primary_key=True, index=True)
    customer_id = Column(String, ForeignKey("applicants.customer_id"))
    risk_track = Column(String)            # prime, subprime, dispute
    overall_risk_level = Column(String)    # LOW, MEDIUM, HIGH, CRITICAL
    compliance_status = Column(String)
    eval_score = Column(Float)
    # The final output generated by the LangGraph pipeline
    final_report = Column(JSON)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
